# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49415a3ca2d90883789ff7b87efc68227463186d2d9f495024be13c2a16fb9c4cf3a5e7c0fbd73387ad25386b7403a41f7f7b4093e79904a3d463ce0d0bdf853

test:
  secret_key_base: e3bbd232f2cf3735a567cb03d95db1e57ed4add977ecf2d44c560dddd8ec044e22188799a8fd3daf22b4804cedddf63743e3b9034d15d1cdd2c07b1bdf37100e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
